### ISSUE TITLE
Some questions about UXUY MPC, sorry other channels (Discord and Telegram) didn't work for me to ask questions.

### ISSUE THREAD

**Issue by johnnynanjiang** [uxuycom/uxuy-docsite#5]
Hi UXUY, 

I'm very interested in your MPC protocol, and have a couple of questions that need your help to clarify.

1. Does UXUY support BTC and other non-EVM coins?
2. How UXUY MPC protocol works, is it permissionless or proprietary?
3. Is UXUY MPC a `n of m` scheme? 

Thanks.

**Comment by max-uxuy** [comment]
> Hi UXUY,
> 
> I'm very interested in your MPC protocol, and have a couple of questions that need your help to clarify.
> 
> 1. Does UXUY support BTC and other non-EVM coins?

We have already support BTC now. 
> 2. How UXUY MPC protocol works, is it permissionless or proprietary?
We are not opensource the MPC protocol now.
> 3. Is UXUY MPC a `n of m` scheme?
Yes we are.
> 
> Thanks.

Thanks for your interesting.

**Comment by johnnynanjiang** [comment]
Thanks @max-uxuy 

```
2. How UXUY MPC protocol works, is it permissionless or proprietary?
We are not opensource the MPC protocol now.
```

Do you have plan to open source it or it won't be open source at all?

**Comment by max-uxuy** [comment]
> Thanks @max-uxuy 
> 
> 
> 
> ```
> 
> 2. How UXUY MPC protocol works, is it permissionless or proprietary?
> 
> We are not opensource the MPC protocol now.
> 
> ```
> 
> 
> 
> Do you have plan to open source it or it won't be open source at all?
> 
> 

The MPC protocol comes from some opensource projects.

**Comment by baxitfund** [comment]
Approved
